import { Box, Button, Chip, Skeleton, Typography } from '@mui/material'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded'
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../auth/context/AuthContext'
import { useDashboard } from '../hooks/useDashboard'
import '../dashboard.css'

function DashboardLoading() { return <Box className="dashboard-loading"><Skeleton variant="text" width="33%" height={26} /><Skeleton variant="text" width="58%" height={74} /><Skeleton variant="rounded" height={282} /><Box className="dashboard-loading-grid"><Skeleton variant="rounded" height={195} /><Skeleton variant="rounded" height={195} /></Box></Box> }
function DashboardError({ retry }) { return <Box className="dashboard-state"><Typography className="dashboard-eyebrow">A QUICK RETRY</Typography><Typography variant="h2">We couldn’t open your command center.</Typography><Typography>Your account is still safe. Check your connection and try loading your plan space again.</Typography><Button variant="contained" startIcon={<RefreshRoundedIcon />} onClick={retry}>Try again</Button></Box> }
function EmptyCommandCenter({ name, groupCount, onStart }) { return <><Box className="dashboard-welcome"><Box><Typography className="dashboard-eyebrow">YOUR COMMAND CENTER</Typography><Typography variant="h1">Good to see you,<br /><em>{name || 'friend'}.</em></Typography><Typography>Your group plans will live here — the people, the decisions, the bookings, and the money.</Typography><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={onStart}>Start a plan</Button></Box><Box className="dashboard-loop" aria-label="The BookKaroYaar planning loop"><Typography>IDEA</Typography><span>→</span><Typography>PEOPLE</Typography><span>→</span><Typography>PLAN</Typography><span>→</span><Typography>BOOK</Typography><span>→</span><Typography>SPLIT</Typography><span>→</span><Typography>DONE</Typography></Box></Box><Box className="dashboard-empty-grid"><Box className="empty-plan-card"><Chip label="YOUR NEXT PLAN" /><Typography variant="h2">One place<br />for the whole plan.</Typography><Typography>Bring the group in first. The decisions, booking details and split all stay connected.</Typography><Button onClick={onStart} endIcon={<ArrowForwardRoundedIcon />}>Start with an idea</Button></Box><Box className="empty-attention-card"><Typography className="dashboard-eyebrow">WHAT NEEDS YOUR ATTENTION?</Typography><Typography variant="h2">Nothing yet.<br /><em>That’s a good start.</em></Typography><Typography>When your group needs a vote, a booking confirmation, or a settlement, it will show up here.</Typography><Box className="attention-line"><span>{String(groupCount || 0).padStart(2, '0')}</span> {groupCount ? `${groupCount} ${groupCount === 1 ? 'group is' : 'groups are'} ready for an idea` : 'No plans are waiting on you'}</Box></Box></Box><Box className="dashboard-pulse"><Box><Typography className="dashboard-eyebrow">GROUP PULSE</Typography><Typography variant="h2">{groupCount ? `${groupCount} ${groupCount === 1 ? 'group' : 'groups'} ready` : 'Your people are'}<br />{groupCount ? 'for a plan.' : 'one plan away.'}</Typography></Box><Box className="pulse-stickers"><span>Who’s in?</span><span>What time?</span><span>Who paid?</span></Box><Typography>This is where shared momentum becomes visible — instead of disappearing into chat.</Typography></Box></> }

export function DashboardPage() { const { user } = useAuth(); const { loading, error, data, retry } = useDashboard(user?.uid); const navigate = useNavigate(); if (loading) return <DashboardLoading />; if (error) return <DashboardError retry={retry} />; return <Box className="dashboard-page"><EmptyCommandCenter name={(data?.profile?.displayName || user?.displayName || '').split(' ')[0]} groupCount={data?.groupCount} onStart={() => navigate('/app/plans')} /></Box> }
