import { GoogleAuthProvider, createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile } from 'firebase/auth'
import { auth } from '../firebase/config'
import { ensureUserProfile } from './profileService'

export async function signUpWithEmail({ displayName, email, password }) { const credential = await createUserWithEmailAndPassword(auth, email.trim(), password); await updateProfile(credential.user, { displayName: displayName.trim() }); await ensureUserProfile(auth.currentUser ?? credential.user); return credential.user }
export async function signInWithEmail({ email, password }) { const credential = await signInWithEmailAndPassword(auth, email.trim(), password); await ensureUserProfile(credential.user); return credential.user }
export async function signInWithGoogle() { const provider = new GoogleAuthProvider(); provider.setCustomParameters({ prompt: 'select_account' }); const credential = await signInWithPopup(auth, provider); await ensureUserProfile(credential.user); return credential.user }
export function sendPasswordReset(email) { return sendPasswordResetEmail(auth, email.trim()) }
export function logOut() { return signOut(auth) }
const messages = { 'auth/email-already-in-use': 'An account already exists with this email. Try logging in instead.', 'auth/invalid-email': 'Enter a valid email address.', 'auth/invalid-credential': 'That email or password does not match our records.', 'auth/user-not-found': 'That email or password does not match our records.', 'auth/wrong-password': 'That email or password does not match our records.', 'auth/weak-password': 'Use a password with at least 6 characters.', 'auth/too-many-requests': 'Too many attempts. Please wait a moment and try again.', 'auth/user-disabled': 'This account has been disabled. Please contact support.', 'auth/popup-closed-by-user': 'Google sign-in was cancelled.', 'auth/popup-blocked': 'Your browser blocked the Google sign-in window. Please allow pop-ups and try again.', 'auth/unauthorized-domain': 'This site is not authorized for Google sign-in. Add this domain in Firebase Authentication settings.', 'auth/operation-not-allowed': 'Google sign-in is not enabled for this Firebase project yet.', 'auth/argument-error': 'Google sign-in is not configured correctly. Please refresh and try again.', 'auth/network-request-failed': 'We could not reach the network. Check your connection and try again.' }
export function getAuthErrorMessage(error) { return messages[error?.code] ?? 'Something went wrong. Please try again.' }
