import { useState } from 'react'
import { Alert, Avatar, Box, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, TextField, Typography } from '@mui/material'
import { PLAN_TYPE_OPTIONS } from '../planConstants'
import { useGroupDetail } from '../../groups/hooks/useGroupDetail'

const emptyPlan = { title: '', type: 'trip', description: '', startAt: '', endAt: '', location: '', coverImageUrl: '' }
const localInput = (value) => value?.toDate ? new Date(value.toDate().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16) : value || ''
export function PlanFormDialog({ open, groups, initialValues, initialGroupId, members = [], selectedMembers = [], onClose, onSubmit }) {
  const [values, setValues] = useState({ ...emptyPlan, ...initialValues, startAt: localInput(initialValues?.startAt), endAt: localInput(initialValues?.endAt) })
  const [groupId, setGroupId] = useState(initialGroupId || groups[0]?.id || '')
  const [selected, setSelected] = useState(selectedMembers.map((member) => member.uid))
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const groupDetail = useGroupDetail(groupId)
  const change = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = async (event) => { event.preventDefault(); if (!values.title.trim() || !values.type || !groupId) { setError('Choose a group and give this plan a title.'); return } setSaving(true); setError(''); try { await onSubmit({ ...values, groupId, selectedMembers: members.filter((member) => selected.includes(member.uid)), startAt: values.startAt ? new Date(values.startAt) : null, endAt: values.endAt ? new Date(values.endAt) : null }); onClose() } catch { setError('We could not save this plan. Please try again.') } finally { setSaving(false) } }
  const roster = groupDetail.members.length ? groupDetail.members : members
  const availableMembers = roster.filter((member) => member.uid !== initialValues?.createdBy)
  return <Dialog open={open} onClose={saving ? undefined : onClose} fullWidth maxWidth="sm" PaperProps={{ className: 'plan-dialog' }}><DialogTitle>{initialValues ? 'Shape the plan' : 'What are we doing?'}</DialogTitle><DialogContent component="form" onSubmit={submit}><Box className="intent-grid">{PLAN_TYPE_OPTIONS.map((option) => <Button key={option.value} className={values.type === option.value ? 'is-selected' : ''} onClick={() => setValues((current) => ({ ...current, type: option.value }))}>{option.label}</Button>)}</Box><FormControl fullWidth sx={{ mt: 2 }}><InputLabel>Which group is this for?</InputLabel><Select value={groupId} label="Which group is this for?" onChange={(event) => setGroupId(event.target.value)} disabled={Boolean(initialValues)}>{groups.map((group) => <MenuItem key={group.id} value={group.id}>{group.name}</MenuItem>)}</Select></FormControl><TextField autoFocus label="Plan title" name="title" value={values.title} onChange={change} disabled={saving} fullWidth required sx={{ mt: 2 }} /><Box className="plan-form-columns"><TextField label="Starts" name="startAt" type="datetime-local" value={values.startAt} onChange={change} InputLabelProps={{ shrink: true }} disabled={saving} /><TextField label="Ends" name="endAt" type="datetime-local" value={values.endAt} onChange={change} InputLabelProps={{ shrink: true }} disabled={saving} /></Box><TextField label="Location" name="location" value={values.location} onChange={change} disabled={saving} fullWidth sx={{ mt: 2 }} /><TextField label="Description" name="description" value={values.description} onChange={change} disabled={saving} fullWidth multiline minRows={2} sx={{ mt: 2 }} /><TextField label="Cover image URL (optional)" name="coverImageUrl" value={values.coverImageUrl} onChange={change} disabled={saving} fullWidth sx={{ mt: 2 }} />{!initialValues && <Box className="member-picker"><Typography className="dashboard-eyebrow">BRING PEOPLE</Typography>{availableMembers.map((member) => <Box className="member-picker-row" key={member.uid}><Checkbox checked={selected.includes(member.uid)} onChange={() => setSelected((current) => current.includes(member.uid) ? current.filter((uid) => uid !== member.uid) : [...current, member.uid])} /><Avatar src={member.photoURLSnapshot || undefined}>{member.displayNameSnapshot?.slice(0, 1)}</Avatar><Typography>{member.displayNameSnapshot}</Typography></Box>)}</Box>}{error && <Alert severity="error" sx={{ mt: 2, borderRadius: 3 }}>{error}</Alert>}<DialogActions sx={{ px: 0, pt: 3 }}><Button onClick={onClose} disabled={saving} color="inherit">Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? 'Saving…' : initialValues ? 'Save changes' : 'Create plan'}</Button></DialogActions></DialogContent></Dialog>
}

export function ItineraryDialog({ open, initialValues, nextOrder, onClose, onSubmit }) {
  const [values, setValues] = useState(() => { const initial = { title: '', type: 'Plan item', startAt: '', endAt: '', location: '', notes: '', order: nextOrder, ...initialValues }; return { ...initial, startAt: localInput(initial.startAt), endAt: localInput(initial.endAt) } })
  const [saving, setSaving] = useState(false)
  const change = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = async (event) => { event.preventDefault(); if (!values.title.trim()) return; setSaving(true); try { await onSubmit({ ...values, startAt: values.startAt ? new Date(values.startAt) : null, endAt: values.endAt ? new Date(values.endAt) : null }); onClose() } finally { setSaving(false) } }
  return <Dialog open={open} onClose={saving ? undefined : onClose} fullWidth maxWidth="xs" PaperProps={{ className: 'plan-dialog' }}><DialogTitle>{initialValues ? 'Edit itinerary item' : 'Add to the itinerary'}</DialogTitle><DialogContent component="form" onSubmit={submit}><TextField autoFocus label="Title" name="title" value={values.title} onChange={change} required fullWidth /><TextField label="Type" name="type" value={values.type} onChange={change} fullWidth sx={{ mt: 2 }} /><Box className="plan-form-columns"><TextField label="Starts" name="startAt" type="datetime-local" value={values.startAt} onChange={change} InputLabelProps={{ shrink: true }} /><TextField label="Ends" name="endAt" type="datetime-local" value={values.endAt} onChange={change} InputLabelProps={{ shrink: true }} /></Box><TextField label="Location" name="location" value={values.location} onChange={change} fullWidth sx={{ mt: 2 }} /><TextField label="Notes" name="notes" value={values.notes} onChange={change} fullWidth multiline minRows={2} sx={{ mt: 2 }} /><DialogActions sx={{ px: 0, pt: 3 }}><Button onClick={onClose} color="inherit">Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? 'Saving…' : 'Save item'}</Button></DialogActions></DialogContent></Dialog>
}