import { useState } from 'react'
import { IconButton, InputAdornment, Link, TextField, Typography } from '@mui/material'
import VisibilityOffRoundedIcon from '@mui/icons-material/VisibilityOffRounded'
import VisibilityRoundedIcon from '@mui/icons-material/VisibilityRounded'
import { Link as RouterLink, useLocation, useNavigate } from 'react-router-dom'
import { AuthDivider, AuthForm, FormError, GoogleButton, SubmitButton } from '../components/AuthFormParts'
import { AuthLayout } from '../components/AuthLayout'
import { useAuth } from '../context/AuthContext'
import { getAuthErrorMessage } from '../../../services/auth/authService'
export function LoginPage() {
  const { signIn, signInWithGoogle } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [values, setValues] = useState({ email: '', password: '' }); const [errors, setErrors] = useState({}); const [formError, setFormError] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const nextPath = location.state?.from?.pathname || location.state?.from || '/app'
  const change = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value })); const validate = () => { const next = {}; if (!/^\S+@\S+\.\S+$/.test(values.email)) next.email = 'Enter a valid email address.'; if (!values.password) next.password = 'Enter your password.'; setErrors(next); return !Object.keys(next).length }
  const submit = async (event) => { event.preventDefault(); setFormError(''); if (!validate()) return; setLoading(true); try { await signIn(values); navigate(nextPath, { replace: true }) } catch (error) { setFormError(getAuthErrorMessage(error)) } finally { setLoading(false) } }; const google = async () => { setFormError(''); setLoading(true); try { await signInWithGoogle(); navigate(nextPath, { replace: true }) } catch (error) { setFormError(getAuthErrorMessage(error)) } finally { setLoading(false) } }
  return <AuthLayout eyebrow="WELCOME BACK" title="Pick up the plan." description="Your people, bookings and shared moments are waiting."><AuthForm onSubmit={submit}><FormError>{formError}</FormError><GoogleButton loading={loading} onClick={google} /><AuthDivider /><TextField label="Email address" name="email" type="email" autoComplete="email" value={values.email} onChange={change} error={Boolean(errors.email)} helperText={errors.email} disabled={loading} fullWidth required /><TextField label="Password" name="password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" value={values.password} onChange={change} error={Boolean(errors.password)} helperText={errors.password} disabled={loading} fullWidth required slotProps={{ input: { endAdornment: <InputAdornment position="end"><IconButton aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((visible) => !visible)} onMouseDown={(event) => event.preventDefault()} edge="end" disabled={loading}>{showPassword ? <VisibilityOffRoundedIcon /> : <VisibilityRoundedIcon />}</IconButton></InputAdornment> } }} /><Link component={RouterLink} to="/forgot-password" underline="hover" sx={{ alignSelf: 'flex-end', color: '#FEC29F', fontWeight: 700, fontSize: 14 }}>Forgot password?</Link><SubmitButton loading={loading}>Log in</SubmitButton></AuthForm><Typography align="center" variant="body2" sx={{ color: 'text.secondary' }}>New around here? <Link component={RouterLink} to="/signup" state={location.state} sx={{ color: '#FEC29F', fontWeight: 800 }}>Create an account</Link></Typography></AuthLayout>
}
