import { useState } from 'react'
import { Alert, Avatar, Box, Button, Skeleton, Stack, Typography } from '@mui/material'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded'
import GroupsRoundedIcon from '@mui/icons-material/GroupsRounded'
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded'
import { Link as RouterLink, useNavigate } from 'react-router-dom'
import { useAuth } from '../../auth/context/AuthContext'
import { createGroup } from '../../../services/groups/groupService'
import { useGroups } from '../hooks/useGroups'
import { GroupFormDialog } from '../components/GroupDialogs'
import { roleLabels } from '../groupConstants'
import '../groups.css'

function MemberPreview({ group }) { return <Box className="group-avatar-stack"><Avatar className="group-avatar-placeholder">{group.name.slice(0, 1).toUpperCase()}</Avatar><Typography>{group.memberCount} {group.memberCount === 1 ? 'member' : 'members'} · {group.membership ? roleLabels[group.membership.role] : 'Member'}</Typography></Box> }
function GroupsLoading() { return <Box className="groups-grid">{[1, 2, 3].map((item) => <Skeleton key={item} variant="rounded" height={235} sx={{ borderRadius: 4 }} />)}</Box> }
function GroupsEmpty({ onCreate }) { return <Box className="groups-empty"><Box className="groups-empty-mark"><GroupsRoundedIcon /></Box><Typography className="dashboard-eyebrow">YOUR PEOPLE, IN ONE PLACE</Typography><Typography variant="h1">No groups yet.<br /><em>Let’s change that.</em></Typography><Typography>A group is where the chat becomes a shared plan. Bring your people together before the next great idea lands.</Typography><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={onCreate}>Create your first group</Button></Box> }
export function GroupsPage() { const { user } = useAuth(); const { loading, error, groups } = useGroups(user?.uid); const [createOpen, setCreateOpen] = useState(false); const navigate = useNavigate(); const create = async (values) => { const id = await createGroup(values, user); navigate(`/app/groups/${id}`) }; return <Box className="groups-page"><Box className="groups-header"><Box><Typography className="dashboard-eyebrow">YOUR PEOPLE</Typography><Typography variant="h1">My groups.</Typography><Typography>Every plan starts with the people who make it happen.</Typography></Box><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => setCreateOpen(true)}>Create group</Button></Box>{loading && <GroupsLoading />}{error && <Alert severity="error" action={<Button startIcon={<RefreshRoundedIcon />} onClick={() => window.location.reload()} color="inherit">Retry</Button>} sx={{ borderRadius: 3 }}>We couldn’t load your groups. Check your connection and try again.</Alert>}{!loading && !error && !groups.length && <GroupsEmpty onCreate={() => setCreateOpen(true)} />}{!loading && !error && groups.length > 0 && <Box className="groups-grid">{groups.map((group) => <Box key={group.id} component={RouterLink} to={`/app/groups/${group.id}`} className="group-card"><Box className="group-card-accent" style={group.coverImageUrl ? { backgroundImage: `url(${group.coverImageUrl})` } : undefined} /><Typography className="group-card-index">GROUP / {group.id.slice(0, 4).toUpperCase()}</Typography><Typography variant="h2">{group.name}</Typography><Typography>{group.description || 'A shared space for the people and plans that matter.'}</Typography><Stack direction="row" justifyContent="space-between" alignItems="end"><MemberPreview group={group} /><ArrowForwardRoundedIcon /></Stack></Box>)}</Box>}<GroupFormDialog open={createOpen} title="Start with your people" onClose={() => setCreateOpen(false)} onSubmit={create} /></Box> }
